name: Update Calendar ICS

on:
  workflow_dispatch:

jobs:
  download-calendar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages  # 👈 checkout the branch you're deploying from

      - name: Download ICS calendar
        run: |
          mkdir -p public
          curl -L "https://outlook.office365.com/owa/calendar/31941d49ba5446068f8d6e9f44174234@student.le.ac.uk/7ab362aa9f974df9b375a4fe05d3c40117474321622843054888/calendar.ics" -o public/my-calendar.ics

      - name: Commit and push updated ICS
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/my-calendar.ics
          git commit -m "🔄 Update calendar.ics via GitHub Action" || echo "No changes to commit"
          git push origin gh-pages  # 👈 push to gh-pages
